import { useState } from 'react';
import { ToolPageLayout } from '@/components/tools/ToolPageLayout';
import { useLanguage } from '@/lib/i18n';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Switch } from '@/components/ui/switch';
import { Textarea } from '@/components/ui/textarea';
import { Copy, Download, Plus, Trash2, FileText } from 'lucide-react';
import { toast } from 'sonner';

interface RobotRule {
  userAgent: string;
  allow: string[];
  disallow: string[];
  crawlDelay?: number;
}

const RobotsTxtGenerator = () => {
  const { isRTL } = useLanguage();
  const [sitemapUrl, setSitemapUrl] = useState('');
  const [host, setHost] = useState('');
  const [rules, setRules] = useState<RobotRule[]>([
    { userAgent: '*', allow: ['/'], disallow: [], crawlDelay: undefined }
  ]);
  const [allowAI, setAllowAI] = useState(true);

  const aiCrawlers = ['GPTBot', 'ChatGPT-User', 'CCBot', 'PerplexityBot', 'anthropic-ai', 'Claude-Web'];

  const generateRobotsTxt = () => {
    let content = '# robots.txt generated by BestToolsHub\n# https://besttoolshub.online\n\n';

    rules.forEach(rule => {
      content += `User-agent: ${rule.userAgent}\n`;
      rule.allow.forEach(path => {
        if (path) content += `Allow: ${path}\n`;
      });
      rule.disallow.forEach(path => {
        if (path) content += `Disallow: ${path}\n`;
      });
      if (rule.crawlDelay) {
        content += `Crawl-delay: ${rule.crawlDelay}\n`;
      }
      content += '\n';
    });

    // AI Crawlers
    if (allowAI) {
      content += '# AI Crawlers - Allowed\n';
      aiCrawlers.forEach(crawler => {
        content += `User-agent: ${crawler}\nAllow: /\n\n`;
      });
    } else {
      content += '# AI Crawlers - Blocked\n';
      aiCrawlers.forEach(crawler => {
        content += `User-agent: ${crawler}\nDisallow: /\n\n`;
      });
    }

    if (sitemapUrl) {
      content += `Sitemap: ${sitemapUrl}\n`;
    }

    if (host) {
      content += `Host: ${host}\n`;
    }

    return content;
  };

  const addRule = () => {
    setRules([...rules, { userAgent: 'Googlebot', allow: [], disallow: [], crawlDelay: undefined }]);
  };

  const removeRule = (index: number) => {
    setRules(rules.filter((_, i) => i !== index));
  };

  const updateRule = (index: number, field: keyof RobotRule, value: any) => {
    const newRules = [...rules];
    newRules[index] = { ...newRules[index], [field]: value };
    setRules(newRules);
  };

  const addPath = (ruleIndex: number, type: 'allow' | 'disallow') => {
    const newRules = [...rules];
    newRules[ruleIndex][type].push('');
    setRules(newRules);
  };

  const updatePath = (ruleIndex: number, type: 'allow' | 'disallow', pathIndex: number, value: string) => {
    const newRules = [...rules];
    newRules[ruleIndex][type][pathIndex] = value;
    setRules(newRules);
  };

  const removePath = (ruleIndex: number, type: 'allow' | 'disallow', pathIndex: number) => {
    const newRules = [...rules];
    newRules[ruleIndex][type] = newRules[ruleIndex][type].filter((_, i) => i !== pathIndex);
    setRules(newRules);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateRobotsTxt());
    toast.success(isRTL ? 'تم النسخ!' : 'Copied!');
  };

  const downloadFile = () => {
    const blob = new Blob([generateRobotsTxt()], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'robots.txt';
    a.click();
    URL.revokeObjectURL(url);
    toast.success(isRTL ? 'تم التحميل!' : 'Downloaded!');
  };

  const commonUserAgents = ['*', 'Googlebot', 'Bingbot', 'Slurp', 'DuckDuckBot', 'Baiduspider', 'YandexBot'];

  return (
    <ToolPageLayout
      title={isRTL ? 'مولد ملف Robots.txt AI' : 'Robots.txt Generator AI'}
      description={isRTL 
        ? 'أنشئ ملف robots.txt احترافي لموقعك. تحكم في فهرسة محركات البحث والذكاء الاصطناعي.' 
        : 'Create a professional robots.txt file for your website. Control search engine and AI indexing.'}
      keywords="robots.txt generator, SEO, search engine optimization, web crawlers, AI crawlers, GPTBot, sitemap"
      article={isRTL 
        ? 'مولد ملف Robots.txt يساعدك على إنشاء ملف robots.txt احترافي للتحكم في كيفية فهرسة محركات البحث وروبوتات الذكاء الاصطناعي لموقعك. يدعم جميع زاحفات محركات البحث الرئيسية وزاحفات الذكاء الاصطناعي مثل GPTBot و PerplexityBot.'
        : 'Robots.txt Generator helps you create a professional robots.txt file to control how search engines and AI bots index your website. Supports all major search engine crawlers and AI crawlers like GPTBot and PerplexityBot.'}
    >
      <div className="max-w-6xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Settings */}
          <div className="space-y-6">
            <div className="bg-card border border-border rounded-xl p-6">
              <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
                <FileText className="w-5 h-5 text-primary" />
                {isRTL ? 'الإعدادات العامة' : 'General Settings'}
              </h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-2">
                    {isRTL ? 'رابط خريطة الموقع' : 'Sitemap URL'}
                  </label>
                  <Input
                    value={sitemapUrl}
                    onChange={(e) => setSitemapUrl(e.target.value)}
                    placeholder="https://example.com/sitemap.xml"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-2">
                    {isRTL ? 'اسم النطاق' : 'Host'}
                  </label>
                  <Input
                    value={host}
                    onChange={(e) => setHost(e.target.value)}
                    placeholder="https://example.com"
                  />
                </div>

                <div className="flex items-center justify-between p-4 bg-muted/50 rounded-lg">
                  <div>
                    <p className="font-medium">{isRTL ? 'السماح لزاحفات الذكاء الاصطناعي' : 'Allow AI Crawlers'}</p>
                    <p className="text-xs text-muted-foreground">
                      GPTBot, PerplexityBot, Claude-Web...
                    </p>
                  </div>
                  <Switch checked={allowAI} onCheckedChange={setAllowAI} />
                </div>
              </div>
            </div>

            {/* Rules */}
            <div className="bg-card border border-border rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-bold">
                  {isRTL ? 'قواعد الزاحفات' : 'Crawler Rules'}
                </h2>
                <Button onClick={addRule} size="sm" variant="outline">
                  <Plus className="w-4 h-4 mr-1" />
                  {isRTL ? 'إضافة قاعدة' : 'Add Rule'}
                </Button>
              </div>

              <div className="space-y-4">
                {rules.map((rule, ruleIndex) => (
                  <div key={ruleIndex} className="border border-border rounded-lg p-4 space-y-3">
                    <div className="flex items-center gap-2">
                      <select
                        value={rule.userAgent}
                        onChange={(e) => updateRule(ruleIndex, 'userAgent', e.target.value)}
                        className="flex-1 px-3 py-2 rounded-lg border border-border bg-background text-sm"
                      >
                        {commonUserAgents.map(ua => (
                          <option key={ua} value={ua}>{ua}</option>
                        ))}
                      </select>
                      {rules.length > 1 && (
                        <Button 
                          onClick={() => removeRule(ruleIndex)} 
                          size="icon" 
                          variant="ghost"
                          className="text-destructive"
                        >
                          <Trash2 className="w-4 h-4" />
                        </Button>
                      )}
                    </div>

                    {/* Allow paths */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm text-green-600 font-medium">Allow</span>
                        <Button onClick={() => addPath(ruleIndex, 'allow')} size="sm" variant="ghost">
                          <Plus className="w-3 h-3" />
                        </Button>
                      </div>
                      {rule.allow.map((path, pathIndex) => (
                        <div key={pathIndex} className="flex gap-2 mb-1">
                          <Input
                            value={path}
                            onChange={(e) => updatePath(ruleIndex, 'allow', pathIndex, e.target.value)}
                            placeholder="/"
                            className="text-sm"
                          />
                          <Button 
                            onClick={() => removePath(ruleIndex, 'allow', pathIndex)} 
                            size="icon" 
                            variant="ghost"
                          >
                            <Trash2 className="w-3 h-3" />
                          </Button>
                        </div>
                      ))}
                    </div>

                    {/* Disallow paths */}
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="text-sm text-red-600 font-medium">Disallow</span>
                        <Button onClick={() => addPath(ruleIndex, 'disallow')} size="sm" variant="ghost">
                          <Plus className="w-3 h-3" />
                        </Button>
                      </div>
                      {rule.disallow.map((path, pathIndex) => (
                        <div key={pathIndex} className="flex gap-2 mb-1">
                          <Input
                            value={path}
                            onChange={(e) => updatePath(ruleIndex, 'disallow', pathIndex, e.target.value)}
                            placeholder="/admin/"
                            className="text-sm"
                          />
                          <Button 
                            onClick={() => removePath(ruleIndex, 'disallow', pathIndex)} 
                            size="icon" 
                            variant="ghost"
                          >
                            <Trash2 className="w-3 h-3" />
                          </Button>
                        </div>
                      ))}
                    </div>

                    {/* Crawl delay */}
                    <div>
                      <label className="text-sm text-muted-foreground">
                        {isRTL ? 'تأخير الزحف (ثواني)' : 'Crawl Delay (seconds)'}
                      </label>
                      <Input
                        type="number"
                        value={rule.crawlDelay || ''}
                        onChange={(e) => updateRule(ruleIndex, 'crawlDelay', e.target.value ? parseInt(e.target.value) : undefined)}
                        placeholder="10"
                        className="mt-1"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Preview */}
          <div className="lg:sticky lg:top-24 h-fit">
            <div className="bg-card border border-border rounded-xl p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-bold">
                  {isRTL ? 'معاينة robots.txt' : 'robots.txt Preview'}
                </h2>
                <div className="flex gap-2">
                  <Button onClick={copyToClipboard} size="sm" variant="outline">
                    <Copy className="w-4 h-4 mr-1" />
                    {isRTL ? 'نسخ' : 'Copy'}
                  </Button>
                  <Button onClick={downloadFile} size="sm">
                    <Download className="w-4 h-4 mr-1" />
                    {isRTL ? 'تحميل' : 'Download'}
                  </Button>
                </div>
              </div>

              <Textarea
                value={generateRobotsTxt()}
                readOnly
                className="font-mono text-sm min-h-[400px] bg-muted/30"
              />
            </div>
          </div>
        </div>
      </div>
    </ToolPageLayout>
  );
};

export default RobotsTxtGenerator;
